name: scan all repos in the org using sub-workflow

on:
  workflow_dispatch:

jobs:
  get-org-repos:
    runs-on: ubuntu-latest
    environment: PrismaCloudEnv
    steps:
      - uses: austenstone/get-org-repos@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
        id: get-org-repos
    outputs:
      repos: ${{ steps.get-org-repos.outputs.repos }}

  call-workflow-batch-checkov-scan:
    needs:
      - get-org-repos
    strategy:
      matrix:
        repos: ${{ fromJson(needs.get-org-repos.outputs.repos) | jq -cM '[_nwise(100)]' }}
      fail-fast: false
    steps:
      - name: Create Repos Input
        run: |
          reposString=$(echo ${{ matrix.repos }} | jq -r '.')
      - uses: ${{ github.repository_owner }}/${{github.repository}}/.github/workflows/batch-checkov-scan.yml@main
        with:
          repos: ${{ reposString }}
        secrets: inherit          