name: scan all repos in the org using sub-workflow

on:
  workflow_dispatch:

jobs:
  get-org-repos:
    runs-on: ubuntu-latest
    environment: PrismaCloudEnv
    steps:
      - uses: austenstone/get-org-repos@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
        id: get-org-repos
      # - name: Create Repos Input
      #   run: |
      #     reposString=$(echo ${{ matrix.repos }} | jq -r '.')
    outputs:
      # repos: ${{ steps.get-org-repos.outputs.repos }}
      repos: ${{ fromJson(steps.get-org-repos.outputs.repos)  | jq -cM '[_nwise(100)]' }}

  call-workflow-batch-checkov-scan:
    needs:
      - get-org-repos
    strategy:
      matrix:
        repos: ${{ join(needs.get-org-repos.outputs.repos, ', ') }}
      fail-fast: false
    uses: ./.github/workflows/batch-checkov-scan.yml
    with:
      repos: ${{ matrix.repos }}
    secrets: inherit          
