name: scan all repos in the org using sub-workflow

on:
  workflow_dispatch:

jobs:
  get-org-repos:
    runs-on: ubuntu-latest
    environment: PrismaCloudEnv
    steps:
      - uses: austenstone/get-org-repos@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
        id: get-org-repos
      - name: Marshall Repos output
        id: repos-output
        run: |
          echo "reposBatch=$(jq -nc ${{steps.get-org-repos.outputs.repos}} | '[_nwise(200)]')" >> "$GITHUB_OUTPUT"
    outputs:
      repos: ${{ steps.repos-output.outputs.reposBatch }}

  call-workflow-batch-checkov-scan:
    needs:
      - get-org-repos
    strategy:
      matrix:
        repos: ${{ needs.get-org-repos.outputs.repos }}
      fail-fast: false
    uses: ./.github/workflows/batch-checkov-scan.yaml
    with:
      repos: ${{ join(matrix.repos, ', ') }}
    secrets: inherit          
